name: Docker Image CI Stable

on:
  release:
    types: [ "published" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/drgnfireyellow/emuweb:stable

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.PACKAGES_ACCESS_TOKEN}}
    - name: Push to GitHub Container Registry
      run: docker push ghcr.io/drgnfireyellow/emuweb:stable
